---
collections:
  - name: ansible.windows
  - name: community.windows
  - name: community.general
  - name: ansible.posix
  - name: community.crypto
  - name: community.postgresql
  - name: community.mongodb