---
roles:
  # --- Windows CIS Roles (Direct Git Source to avoid Galaxy 404s) ---
  - name: ansible-lockdown.Windows-2019-CIS
    src: https://github.com/ansible-lockdown/Windows-2019-CIS
    scm: git

  - name: ansible-lockdown.Windows-2022-CIS
    src: https://github.com/ansible-lockdown/Windows-2022-CIS
    scm: git

  - name: ansible-lockdown.rhel9_cis
      src: https://github.com/ansible-lockdown/RHEL9-CIS.git
      scm: git
