---
- name: Backup Snapshot and Validation
  hosts: jp_rhel, jp_windows
  gather_facts: 
  vars:
    # Snapshot configuration
    snapshot_time: "{{ now(fmt='%Y-%m-%d_%H-%M-%S') }}
    snapshot_description: "Automated backup before security patching activity"

  tasks:
    # 1. INITIAL ANNOUNCEMENT
    - name: Notify start of activity
      ansible.builtin.debug:
        msg: "CRITICAL: Starting pre-automation backup snapshots for all targeted hosts."

    # 2. THE 5-SECOND PAUSE
    - name: Pauseto allow storage commit
      ansible.builtin.pause:
        seconds: 5


    # 3. FINAL SUCCESS MESSAGE
    - name: Notify successful completion
      ansible.builtin.debug:
        msg: "SUCCESS: Snapshot backup_{{ inventory_hostname }}_{{ snapshot_time }} has been successfully completed."
    
    - name: Set fact cache for snapshot result
      ansible.builtin.set_fact:
        chached_snapshot_name: "backup_{{ inventory_hostname }}_{{ snapshot_time }}"
        cacheable: true
