---
- name: Remove Firefox from RHEL fleet
  hosts: jp_rhel
  become: yes
  tasks:
    - name: Uninstall Firefox package
      ansible.builtin.dnf:
        name: firefox
        state: absent
        autoremove: yes  # This cleans up unused dependencies